### ISSUE TITLE
原img标签未设置data-src属性时，插件加载图片失败，代码大概在如下位置，看大佬要不要改下^_^

### ISSUE THREAD

**Issue by MD-luffy** [daxiazilong/imagePreview#3]
triggerItems.forEach(function (element, index) {
            // fix bug，img未设置dataset属性的时候导致加载预览图片失败
            images.push(element.dataset.src || element.src);
        });

**Comment by daxiazilong** [comment]
首先谢谢你的反馈哈，最近一直忙别的事，今天才看到这个，起初想的是大多数项目里缩略图和预览大图的的源路径（src）肯定是不一样的，毕竟较小的图比较节省流量，所以想当然觉得肯定会有datasrc，确实没有考虑到你上边提到的这个需求，暂时决定下个版本修复。
`有同样问题的同学可以参照下上边luffy的解决方式`
