### ISSUE TITLE
大佬，支持缩放的api调用么？我看代码好像没有

### ISSUE THREAD

**Issue by wweggplant** [daxiazilong/imagePreview#49]

**Comment by daxiazilong** [comment]
整个previewer的缩放 可以自己最外层套个transform实现； 你具体业务需求是啥呢

**Comment by wweggplant** [comment]
> 整个previewer的缩放 可以自己最外层套个transform实现； 你具体业务需求是啥呢

我想实现的打开图片自动放大1.5倍，场景是手机上预览table图片的数据。目前已经实现table转图片了

**Comment by daxiazilong** [comment]
> > 整个previewer的缩放 可以自己最外层套个transform实现； 你具体业务需求是啥呢
> 
> 我想实现的打开图片自动放大1.5倍，场景是手机上预览table图片的数据。目前已经实现table转图片了

![image](https://github.com/user-attachments/assets/8aaa901e-9018-42e8-8fdb-401862bc2232)

研究研究这个方法看看 文档上没有 实际是可以通过ImagePreview实例拿得到的哈

**Comment by daxiazilong** [comment]
> > 整个previewer的缩放 可以自己最外层套个transform实现； 你具体业务需求是啥呢
> 
> 我想实现的打开图片自动放大1.5倍，场景是手机上预览table图片的数据。目前已经实现table转图片了

还有没有其他问题 小老弟 没有的话我就关掉issuse哈
